/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SelectRepoRouteImport } from './routes/select-repo'
import { Route as ReposRouteImport } from './routes/repos'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NotchTestRouteImport } from './routes/notch/test'
import { Route as ApiOauthClientMetadataRouteImport } from './routes/api/oauth/client-metadata'
import { Route as ApiNotchMeRouteImport } from './routes/api/notch/me'
import { Route as ApiAgentStreamRouteImport } from './routes/api/agent/stream'
import { Route as ApiAgentSessionRouteImport } from './routes/api/agent/session'
import { Route as ApiAgentMessageRouteImport } from './routes/api/agent/message'

const SelectRepoRoute = SelectRepoRouteImport.update({
  id: '/select-repo',
  path: '/select-repo',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposRoute = ReposRouteImport.update({
  id: '/repos',
  path: '/repos',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotchTestRoute = NotchTestRouteImport.update({
  id: '/notch/test',
  path: '/notch/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthClientMetadataRoute = ApiOauthClientMetadataRouteImport.update({
  id: '/api/oauth/client-metadata',
  path: '/api/oauth/client-metadata',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotchMeRoute = ApiNotchMeRouteImport.update({
  id: '/api/notch/me',
  path: '/api/notch/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentStreamRoute = ApiAgentStreamRouteImport.update({
  id: '/api/agent/stream',
  path: '/api/agent/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentSessionRoute = ApiAgentSessionRouteImport.update({
  id: '/api/agent/session',
  path: '/api/agent/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentMessageRoute = ApiAgentMessageRouteImport.update({
  id: '/api/agent/message',
  path: '/api/agent/message',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/callback': typeof CallbackRoute
  '/dashboard': typeof DashboardRoute
  '/repos': typeof ReposRoute
  '/select-repo': typeof SelectRepoRoute
  '/notch/test': typeof NotchTestRoute
  '/api/agent/message': typeof ApiAgentMessageRoute
  '/api/agent/session': typeof ApiAgentSessionRoute
  '/api/agent/stream': typeof ApiAgentStreamRoute
  '/api/notch/me': typeof ApiNotchMeRoute
  '/api/oauth/client-metadata': typeof ApiOauthClientMetadataRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/callback': typeof CallbackRoute
  '/dashboard': typeof DashboardRoute
  '/repos': typeof ReposRoute
  '/select-repo': typeof SelectRepoRoute
  '/notch/test': typeof NotchTestRoute
  '/api/agent/message': typeof ApiAgentMessageRoute
  '/api/agent/session': typeof ApiAgentSessionRoute
  '/api/agent/stream': typeof ApiAgentStreamRoute
  '/api/notch/me': typeof ApiNotchMeRoute
  '/api/oauth/client-metadata': typeof ApiOauthClientMetadataRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/callback': typeof CallbackRoute
  '/dashboard': typeof DashboardRoute
  '/repos': typeof ReposRoute
  '/select-repo': typeof SelectRepoRoute
  '/notch/test': typeof NotchTestRoute
  '/api/agent/message': typeof ApiAgentMessageRoute
  '/api/agent/session': typeof ApiAgentSessionRoute
  '/api/agent/stream': typeof ApiAgentStreamRoute
  '/api/notch/me': typeof ApiNotchMeRoute
  '/api/oauth/client-metadata': typeof ApiOauthClientMetadataRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent'
    | '/callback'
    | '/dashboard'
    | '/repos'
    | '/select-repo'
    | '/notch/test'
    | '/api/agent/message'
    | '/api/agent/session'
    | '/api/agent/stream'
    | '/api/notch/me'
    | '/api/oauth/client-metadata'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent'
    | '/callback'
    | '/dashboard'
    | '/repos'
    | '/select-repo'
    | '/notch/test'
    | '/api/agent/message'
    | '/api/agent/session'
    | '/api/agent/stream'
    | '/api/notch/me'
    | '/api/oauth/client-metadata'
  id:
    | '__root__'
    | '/'
    | '/agent'
    | '/callback'
    | '/dashboard'
    | '/repos'
    | '/select-repo'
    | '/notch/test'
    | '/api/agent/message'
    | '/api/agent/session'
    | '/api/agent/stream'
    | '/api/notch/me'
    | '/api/oauth/client-metadata'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentRoute: typeof AgentRoute
  CallbackRoute: typeof CallbackRoute
  DashboardRoute: typeof DashboardRoute
  ReposRoute: typeof ReposRoute
  SelectRepoRoute: typeof SelectRepoRoute
  NotchTestRoute: typeof NotchTestRoute
  ApiAgentMessageRoute: typeof ApiAgentMessageRoute
  ApiAgentSessionRoute: typeof ApiAgentSessionRoute
  ApiAgentStreamRoute: typeof ApiAgentStreamRoute
  ApiNotchMeRoute: typeof ApiNotchMeRoute
  ApiOauthClientMetadataRoute: typeof ApiOauthClientMetadataRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/select-repo': {
      id: '/select-repo'
      path: '/select-repo'
      fullPath: '/select-repo'
      preLoaderRoute: typeof SelectRepoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos': {
      id: '/repos'
      path: '/repos'
      fullPath: '/repos'
      preLoaderRoute: typeof ReposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notch/test': {
      id: '/notch/test'
      path: '/notch/test'
      fullPath: '/notch/test'
      preLoaderRoute: typeof NotchTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/client-metadata': {
      id: '/api/oauth/client-metadata'
      path: '/api/oauth/client-metadata'
      fullPath: '/api/oauth/client-metadata'
      preLoaderRoute: typeof ApiOauthClientMetadataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notch/me': {
      id: '/api/notch/me'
      path: '/api/notch/me'
      fullPath: '/api/notch/me'
      preLoaderRoute: typeof ApiNotchMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/stream': {
      id: '/api/agent/stream'
      path: '/api/agent/stream'
      fullPath: '/api/agent/stream'
      preLoaderRoute: typeof ApiAgentStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/session': {
      id: '/api/agent/session'
      path: '/api/agent/session'
      fullPath: '/api/agent/session'
      preLoaderRoute: typeof ApiAgentSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/message': {
      id: '/api/agent/message'
      path: '/api/agent/message'
      fullPath: '/api/agent/message'
      preLoaderRoute: typeof ApiAgentMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentRoute: AgentRoute,
  CallbackRoute: CallbackRoute,
  DashboardRoute: DashboardRoute,
  ReposRoute: ReposRoute,
  SelectRepoRoute: SelectRepoRoute,
  NotchTestRoute: NotchTestRoute,
  ApiAgentMessageRoute: ApiAgentMessageRoute,
  ApiAgentSessionRoute: ApiAgentSessionRoute,
  ApiAgentStreamRoute: ApiAgentStreamRoute,
  ApiNotchMeRoute: ApiNotchMeRoute,
  ApiOauthClientMetadataRoute: ApiOauthClientMetadataRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
