/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SitesIndexRouteImport } from './routes/sites/index'
import { Route as SetupTangledRouteImport } from './routes/setup/tangled'
import { Route as SetupScriptRouteImport } from './routes/setup/script'
import { Route as NotchTestRouteImport } from './routes/notch/test'
import { Route as SitesDomainBuilderRouteImport } from './routes/sites/$domain/builder'
import { Route as ApiOauthClientMetadataRouteImport } from './routes/api/oauth/client-metadata'
import { Route as ApiNotchSiteRouteImport } from './routes/api/notch/site'
import { Route as ApiNotchNotificationsRouteImport } from './routes/api/notch/notifications'
import { Route as ApiNotchMeRouteImport } from './routes/api/notch/me'
import { Route as ApiNotchFollowsRouteImport } from './routes/api/notch/follows'
import { Route as ApiNotchFollowersRouteImport } from './routes/api/notch/followers'
import { Route as ApiNotchConversationsRouteImport } from './routes/api/notch/conversations'
import { Route as ApiNotchCheckRouteImport } from './routes/api/notch/check'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAgentUploadRouteImport } from './routes/api/agent/upload'
import { Route as ApiAgentStreamRouteImport } from './routes/api/agent/stream'
import { Route as ApiAgentSessionRouteImport } from './routes/api/agent/session'
import { Route as ApiAgentPushRouteImport } from './routes/api/agent/push'
import { Route as ApiNotchConversationsPeerIdRouteImport } from './routes/api/notch/conversations/$peerId'
import { Route as ApiNotchConversationsPeerIdMessagesRouteImport } from './routes/api/notch/conversations/$peerId/messages'

const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesIndexRoute = SitesIndexRouteImport.update({
  id: '/sites/',
  path: '/sites/',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupTangledRoute = SetupTangledRouteImport.update({
  id: '/setup/tangled',
  path: '/setup/tangled',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupScriptRoute = SetupScriptRouteImport.update({
  id: '/setup/script',
  path: '/setup/script',
  getParentRoute: () => rootRouteImport,
} as any)
const NotchTestRoute = NotchTestRouteImport.update({
  id: '/notch/test',
  path: '/notch/test',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesDomainBuilderRoute = SitesDomainBuilderRouteImport.update({
  id: '/sites/$domain/builder',
  path: '/sites/$domain/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthClientMetadataRoute = ApiOauthClientMetadataRouteImport.update({
  id: '/api/oauth/client-metadata',
  path: '/api/oauth/client-metadata',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotchSiteRoute = ApiNotchSiteRouteImport.update({
  id: '/api/notch/site',
  path: '/api/notch/site',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotchNotificationsRoute = ApiNotchNotificationsRouteImport.update({
  id: '/api/notch/notifications',
  path: '/api/notch/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotchMeRoute = ApiNotchMeRouteImport.update({
  id: '/api/notch/me',
  path: '/api/notch/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotchFollowsRoute = ApiNotchFollowsRouteImport.update({
  id: '/api/notch/follows',
  path: '/api/notch/follows',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotchFollowersRoute = ApiNotchFollowersRouteImport.update({
  id: '/api/notch/followers',
  path: '/api/notch/followers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotchConversationsRoute = ApiNotchConversationsRouteImport.update({
  id: '/api/notch/conversations',
  path: '/api/notch/conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotchCheckRoute = ApiNotchCheckRouteImport.update({
  id: '/api/notch/check',
  path: '/api/notch/check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentUploadRoute = ApiAgentUploadRouteImport.update({
  id: '/api/agent/upload',
  path: '/api/agent/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentStreamRoute = ApiAgentStreamRouteImport.update({
  id: '/api/agent/stream',
  path: '/api/agent/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentSessionRoute = ApiAgentSessionRouteImport.update({
  id: '/api/agent/session',
  path: '/api/agent/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentPushRoute = ApiAgentPushRouteImport.update({
  id: '/api/agent/push',
  path: '/api/agent/push',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotchConversationsPeerIdRoute =
  ApiNotchConversationsPeerIdRouteImport.update({
    id: '/$peerId',
    path: '/$peerId',
    getParentRoute: () => ApiNotchConversationsRoute,
  } as any)
const ApiNotchConversationsPeerIdMessagesRoute =
  ApiNotchConversationsPeerIdMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => ApiNotchConversationsPeerIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/notch/test': typeof NotchTestRoute
  '/setup/script': typeof SetupScriptRoute
  '/setup/tangled': typeof SetupTangledRoute
  '/sites/': typeof SitesIndexRoute
  '/api/agent/push': typeof ApiAgentPushRoute
  '/api/agent/session': typeof ApiAgentSessionRoute
  '/api/agent/stream': typeof ApiAgentStreamRoute
  '/api/agent/upload': typeof ApiAgentUploadRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/notch/check': typeof ApiNotchCheckRoute
  '/api/notch/conversations': typeof ApiNotchConversationsRouteWithChildren
  '/api/notch/followers': typeof ApiNotchFollowersRoute
  '/api/notch/follows': typeof ApiNotchFollowsRoute
  '/api/notch/me': typeof ApiNotchMeRoute
  '/api/notch/notifications': typeof ApiNotchNotificationsRoute
  '/api/notch/site': typeof ApiNotchSiteRoute
  '/api/oauth/client-metadata': typeof ApiOauthClientMetadataRoute
  '/sites/$domain/builder': typeof SitesDomainBuilderRoute
  '/api/notch/conversations/$peerId': typeof ApiNotchConversationsPeerIdRouteWithChildren
  '/api/notch/conversations/$peerId/messages': typeof ApiNotchConversationsPeerIdMessagesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/notch/test': typeof NotchTestRoute
  '/setup/script': typeof SetupScriptRoute
  '/setup/tangled': typeof SetupTangledRoute
  '/sites': typeof SitesIndexRoute
  '/api/agent/push': typeof ApiAgentPushRoute
  '/api/agent/session': typeof ApiAgentSessionRoute
  '/api/agent/stream': typeof ApiAgentStreamRoute
  '/api/agent/upload': typeof ApiAgentUploadRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/notch/check': typeof ApiNotchCheckRoute
  '/api/notch/conversations': typeof ApiNotchConversationsRouteWithChildren
  '/api/notch/followers': typeof ApiNotchFollowersRoute
  '/api/notch/follows': typeof ApiNotchFollowsRoute
  '/api/notch/me': typeof ApiNotchMeRoute
  '/api/notch/notifications': typeof ApiNotchNotificationsRoute
  '/api/notch/site': typeof ApiNotchSiteRoute
  '/api/oauth/client-metadata': typeof ApiOauthClientMetadataRoute
  '/sites/$domain/builder': typeof SitesDomainBuilderRoute
  '/api/notch/conversations/$peerId': typeof ApiNotchConversationsPeerIdRouteWithChildren
  '/api/notch/conversations/$peerId/messages': typeof ApiNotchConversationsPeerIdMessagesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/notch/test': typeof NotchTestRoute
  '/setup/script': typeof SetupScriptRoute
  '/setup/tangled': typeof SetupTangledRoute
  '/sites/': typeof SitesIndexRoute
  '/api/agent/push': typeof ApiAgentPushRoute
  '/api/agent/session': typeof ApiAgentSessionRoute
  '/api/agent/stream': typeof ApiAgentStreamRoute
  '/api/agent/upload': typeof ApiAgentUploadRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/notch/check': typeof ApiNotchCheckRoute
  '/api/notch/conversations': typeof ApiNotchConversationsRouteWithChildren
  '/api/notch/followers': typeof ApiNotchFollowersRoute
  '/api/notch/follows': typeof ApiNotchFollowsRoute
  '/api/notch/me': typeof ApiNotchMeRoute
  '/api/notch/notifications': typeof ApiNotchNotificationsRoute
  '/api/notch/site': typeof ApiNotchSiteRoute
  '/api/oauth/client-metadata': typeof ApiOauthClientMetadataRoute
  '/sites/$domain/builder': typeof SitesDomainBuilderRoute
  '/api/notch/conversations/$peerId': typeof ApiNotchConversationsPeerIdRouteWithChildren
  '/api/notch/conversations/$peerId/messages': typeof ApiNotchConversationsPeerIdMessagesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/notch/test'
    | '/setup/script'
    | '/setup/tangled'
    | '/sites/'
    | '/api/agent/push'
    | '/api/agent/session'
    | '/api/agent/stream'
    | '/api/agent/upload'
    | '/api/auth/$'
    | '/api/notch/check'
    | '/api/notch/conversations'
    | '/api/notch/followers'
    | '/api/notch/follows'
    | '/api/notch/me'
    | '/api/notch/notifications'
    | '/api/notch/site'
    | '/api/oauth/client-metadata'
    | '/sites/$domain/builder'
    | '/api/notch/conversations/$peerId'
    | '/api/notch/conversations/$peerId/messages'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/notch/test'
    | '/setup/script'
    | '/setup/tangled'
    | '/sites'
    | '/api/agent/push'
    | '/api/agent/session'
    | '/api/agent/stream'
    | '/api/agent/upload'
    | '/api/auth/$'
    | '/api/notch/check'
    | '/api/notch/conversations'
    | '/api/notch/followers'
    | '/api/notch/follows'
    | '/api/notch/me'
    | '/api/notch/notifications'
    | '/api/notch/site'
    | '/api/oauth/client-metadata'
    | '/sites/$domain/builder'
    | '/api/notch/conversations/$peerId'
    | '/api/notch/conversations/$peerId/messages'
  id:
    | '__root__'
    | '/'
    | '/callback'
    | '/notch/test'
    | '/setup/script'
    | '/setup/tangled'
    | '/sites/'
    | '/api/agent/push'
    | '/api/agent/session'
    | '/api/agent/stream'
    | '/api/agent/upload'
    | '/api/auth/$'
    | '/api/notch/check'
    | '/api/notch/conversations'
    | '/api/notch/followers'
    | '/api/notch/follows'
    | '/api/notch/me'
    | '/api/notch/notifications'
    | '/api/notch/site'
    | '/api/oauth/client-metadata'
    | '/sites/$domain/builder'
    | '/api/notch/conversations/$peerId'
    | '/api/notch/conversations/$peerId/messages'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CallbackRoute: typeof CallbackRoute
  NotchTestRoute: typeof NotchTestRoute
  SetupScriptRoute: typeof SetupScriptRoute
  SetupTangledRoute: typeof SetupTangledRoute
  SitesIndexRoute: typeof SitesIndexRoute
  ApiAgentPushRoute: typeof ApiAgentPushRoute
  ApiAgentSessionRoute: typeof ApiAgentSessionRoute
  ApiAgentStreamRoute: typeof ApiAgentStreamRoute
  ApiAgentUploadRoute: typeof ApiAgentUploadRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiNotchCheckRoute: typeof ApiNotchCheckRoute
  ApiNotchConversationsRoute: typeof ApiNotchConversationsRouteWithChildren
  ApiNotchFollowersRoute: typeof ApiNotchFollowersRoute
  ApiNotchFollowsRoute: typeof ApiNotchFollowsRoute
  ApiNotchMeRoute: typeof ApiNotchMeRoute
  ApiNotchNotificationsRoute: typeof ApiNotchNotificationsRoute
  ApiNotchSiteRoute: typeof ApiNotchSiteRoute
  ApiOauthClientMetadataRoute: typeof ApiOauthClientMetadataRoute
  SitesDomainBuilderRoute: typeof SitesDomainBuilderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/': {
      id: '/sites/'
      path: '/sites'
      fullPath: '/sites/'
      preLoaderRoute: typeof SitesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/tangled': {
      id: '/setup/tangled'
      path: '/setup/tangled'
      fullPath: '/setup/tangled'
      preLoaderRoute: typeof SetupTangledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/script': {
      id: '/setup/script'
      path: '/setup/script'
      fullPath: '/setup/script'
      preLoaderRoute: typeof SetupScriptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notch/test': {
      id: '/notch/test'
      path: '/notch/test'
      fullPath: '/notch/test'
      preLoaderRoute: typeof NotchTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/$domain/builder': {
      id: '/sites/$domain/builder'
      path: '/sites/$domain/builder'
      fullPath: '/sites/$domain/builder'
      preLoaderRoute: typeof SitesDomainBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/client-metadata': {
      id: '/api/oauth/client-metadata'
      path: '/api/oauth/client-metadata'
      fullPath: '/api/oauth/client-metadata'
      preLoaderRoute: typeof ApiOauthClientMetadataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notch/site': {
      id: '/api/notch/site'
      path: '/api/notch/site'
      fullPath: '/api/notch/site'
      preLoaderRoute: typeof ApiNotchSiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notch/notifications': {
      id: '/api/notch/notifications'
      path: '/api/notch/notifications'
      fullPath: '/api/notch/notifications'
      preLoaderRoute: typeof ApiNotchNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notch/me': {
      id: '/api/notch/me'
      path: '/api/notch/me'
      fullPath: '/api/notch/me'
      preLoaderRoute: typeof ApiNotchMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notch/follows': {
      id: '/api/notch/follows'
      path: '/api/notch/follows'
      fullPath: '/api/notch/follows'
      preLoaderRoute: typeof ApiNotchFollowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notch/followers': {
      id: '/api/notch/followers'
      path: '/api/notch/followers'
      fullPath: '/api/notch/followers'
      preLoaderRoute: typeof ApiNotchFollowersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notch/conversations': {
      id: '/api/notch/conversations'
      path: '/api/notch/conversations'
      fullPath: '/api/notch/conversations'
      preLoaderRoute: typeof ApiNotchConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notch/check': {
      id: '/api/notch/check'
      path: '/api/notch/check'
      fullPath: '/api/notch/check'
      preLoaderRoute: typeof ApiNotchCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/upload': {
      id: '/api/agent/upload'
      path: '/api/agent/upload'
      fullPath: '/api/agent/upload'
      preLoaderRoute: typeof ApiAgentUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/stream': {
      id: '/api/agent/stream'
      path: '/api/agent/stream'
      fullPath: '/api/agent/stream'
      preLoaderRoute: typeof ApiAgentStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/session': {
      id: '/api/agent/session'
      path: '/api/agent/session'
      fullPath: '/api/agent/session'
      preLoaderRoute: typeof ApiAgentSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/push': {
      id: '/api/agent/push'
      path: '/api/agent/push'
      fullPath: '/api/agent/push'
      preLoaderRoute: typeof ApiAgentPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notch/conversations/$peerId': {
      id: '/api/notch/conversations/$peerId'
      path: '/$peerId'
      fullPath: '/api/notch/conversations/$peerId'
      preLoaderRoute: typeof ApiNotchConversationsPeerIdRouteImport
      parentRoute: typeof ApiNotchConversationsRoute
    }
    '/api/notch/conversations/$peerId/messages': {
      id: '/api/notch/conversations/$peerId/messages'
      path: '/messages'
      fullPath: '/api/notch/conversations/$peerId/messages'
      preLoaderRoute: typeof ApiNotchConversationsPeerIdMessagesRouteImport
      parentRoute: typeof ApiNotchConversationsPeerIdRoute
    }
  }
}

interface ApiNotchConversationsPeerIdRouteChildren {
  ApiNotchConversationsPeerIdMessagesRoute: typeof ApiNotchConversationsPeerIdMessagesRoute
}

const ApiNotchConversationsPeerIdRouteChildren: ApiNotchConversationsPeerIdRouteChildren =
  {
    ApiNotchConversationsPeerIdMessagesRoute:
      ApiNotchConversationsPeerIdMessagesRoute,
  }

const ApiNotchConversationsPeerIdRouteWithChildren =
  ApiNotchConversationsPeerIdRoute._addFileChildren(
    ApiNotchConversationsPeerIdRouteChildren,
  )

interface ApiNotchConversationsRouteChildren {
  ApiNotchConversationsPeerIdRoute: typeof ApiNotchConversationsPeerIdRouteWithChildren
}

const ApiNotchConversationsRouteChildren: ApiNotchConversationsRouteChildren = {
  ApiNotchConversationsPeerIdRoute:
    ApiNotchConversationsPeerIdRouteWithChildren,
}

const ApiNotchConversationsRouteWithChildren =
  ApiNotchConversationsRoute._addFileChildren(
    ApiNotchConversationsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CallbackRoute: CallbackRoute,
  NotchTestRoute: NotchTestRoute,
  SetupScriptRoute: SetupScriptRoute,
  SetupTangledRoute: SetupTangledRoute,
  SitesIndexRoute: SitesIndexRoute,
  ApiAgentPushRoute: ApiAgentPushRoute,
  ApiAgentSessionRoute: ApiAgentSessionRoute,
  ApiAgentStreamRoute: ApiAgentStreamRoute,
  ApiAgentUploadRoute: ApiAgentUploadRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiNotchCheckRoute: ApiNotchCheckRoute,
  ApiNotchConversationsRoute: ApiNotchConversationsRouteWithChildren,
  ApiNotchFollowersRoute: ApiNotchFollowersRoute,
  ApiNotchFollowsRoute: ApiNotchFollowsRoute,
  ApiNotchMeRoute: ApiNotchMeRoute,
  ApiNotchNotificationsRoute: ApiNotchNotificationsRoute,
  ApiNotchSiteRoute: ApiNotchSiteRoute,
  ApiOauthClientMetadataRoute: ApiOauthClientMetadataRoute,
  SitesDomainBuilderRoute: SitesDomainBuilderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
